apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m

  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: source-tc-traefik
        namespace: flux-system
      reconcileStrategy: Revision

  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback

  driftDetection:
    mode: enabled

  values: {}
