traefik:
  deployment:
    kind: Deployment
    replicas: 2

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  ingressClass:
    enabled: true
    isDefaultClass: true

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: ["traefik"]
    healthcheck:
      enabled: true
      entryPoints: ["traefik"]

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: false
      allowExternalNameServices: false
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: false
      publishedService:
        enabled: true
    kubernetesGateway:
      enabled: false

  log:
    level: INFO
    format: json

  accessLog:
    enabled: true
    format: json

  metrics:
    prometheus:
      entryPoint: traefik

  ports:
    traefik:
      port: 8080
      expose:
        default: false
    web:
      port: 8000
      exposedPort: 80
      expose:
        default: true
    websecure:
      port: 8443
      exposedPort: 443
      expose:
        default: true
      http:
        tls:
          enabled: true

  service:
    enabled: true
    single: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: traefik

