apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  CLUSTER: tc-dev-euc1
  ENV: dev
  REGION: eu-central-1
  TRAEFIK_VERSION: 1.0.0
  METRICS_SERVER_VERSION: 3.13.1
  KEYCLOAK_VERSION: 7.2.2
