apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    traefik:
      log:
        level: DEBUG
      deployment:
        replicas: 1
      podDisruptionBudget:
        enabled: false
