apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
      limits:
        cpu: 1500m
        memory: 2048Mi
    database:
      vendor: dev-file
    args:
      - start-dev
    extraEnv: |
      - name: KC_HOSTNAME
        value: http://keycloak.localhost:8080
      - name: KC_LOG_LEVEL
        value: INFO
    http:
      relativePath: "/"
    extraEnvFrom: |
      - secretRef:
          name: keycloak-secrets
    proxy:
      mode: xforwarded
    ingress:
      enabled: true
      ingressClassName: traefik
      rules:
        - host: keycloak.localhost
          paths:
            - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
              pathType: Prefix
