apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    traefik:
      deployment:
        replicas: 2
      service:
        spec:
          type: NodePort
      ports:
        web:
          nodePort: 30080
        websecure:
          nodePort: 30443
